export const TICK_RATE = 20; // Hz
export const TICK_INTERVAL_MS = 1000 / TICK_RATE;
export const WORLD_RADIUS = 40;
export const PLAYER_RADIUS = 1.1;
export const ORB_RADIUS = 0.75;
export const MAX_SPEED = 12;
export const MAX_ACCELERATION = 24;
export const FRICTION = 0.82;
export const DASH_SPEED_BOOST = 18;
export const DASH_COOLDOWN_MS = 2000;
export const DASH_DURATION_MS = 150;
export const DASH_FX_DURATION_MS = 350;
export const TAG_RADIUS = 2.5;
export const TAG_SLOW_DURATION_MS = 1500;
export const TAG_SLOW_MULTIPLIER = 0.45;
export const ORB_RESPAWN_DELAY_MS = 500;
export const STARTING_ORB_COUNT = 10;
export const ORB_SCORE_VALUE = 1;
